language: ruby
cache: bundler
sudo: false

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external

env:
  global:
     # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
