title: David Singleton
url: http://dsingleton.co.uk/
author: David Singleton

permalink: /blog/:title
markdown: kramdown
highlighter: rouge

# Enforce github-pages compatability: https://jekyllrb.com/docs/plugins/
safe: true

exclude:
  - README
  - Gemfile
  - Gemfile.lock
  - .ruby-version

gems:
  - jekyll-feed

feed:
  path: atom.xml
