markdown: kramdown
title: David Singleton
author: David Singleton
highlighter: true
exclude:
  - README
  - Gemfile
  - Gemfile.lock
permalink: /blog/:title
url: http://dsingleton.co.uk/

gems:
  - jekyll-feed

feed:
  path: atom.xml
