title: David Singleton
url: http://dsingleton.co.uk/
author: David Singleton

permalink: /blog/:title
markdown: kramdown
highlighter: rouge

# Enforce github-pages compatability: https://jekyllrb.com/docs/plugins/
safe: true

# GA tracking ID
analytics_id: UA-609105-1

exclude:
  - README
  - Gemfile
  - Gemfile.lock
  - .ruby-version

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

feed:
  path: atom.xml

sass:
  style: :compressed
